name: Build, Push, and Deploy

on:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: fabulous-badger-1711210691

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dockerhub Login
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - uses: actions/checkout@v2
  #     - name: list files
  #       run: ls -l
  #     - name: Build image
  #       run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/simple_flask_app:latest -f Dockerfile .
  #     - name: Push image
  #       run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple_flask_app:latest
  
  deploy:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Show contents of deployment file
        run: cat deployment.yaml
     
      - name: kubectl current context
        run: kubectl config current-context
     
      - name: kubectl get iamidentitymapping
        run: eksctl get iamidentitymapping --cluster $EKS_CLUSTER_NAME

      - name: test kubectl version
        run: kubectl version
     
      - name: test kubectl get all
        run: kubectl get all

      - name: Deploy to EKS
        run: kubectl apply -f deployment.yaml
