name: Build, Push, and Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dockerhub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: list files
        run: ls -l
      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/simple_flask_app:latest -f Dockerfile .
      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple_flask_app:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
      - name: Apply Kubernetes manifests
        run: kubectl apply -f deployment.yaml
        env:
          # encoding your kubeconfig file as base64 and adding it as a secret in GitHub
          KUBECONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
